import type { Paper } from "./types";

export const VEROS_PAPERS: Paper[] = [
  {
    id: "2402.09876",
    title: "Mixture-of-Depths: Compute-Optimal Conditional Routing in Decoder-Only Transformers",
    authors: "Park, Adesope, Liu, Vasquez, Friedman",
    tldr:
      "Proposes a token-routed depth allocation that lets each token use a learned subset of layers; matches dense baselines at 60% of the FLOPs and reveals a clean compute–quality frontier.",
    venue: "ICLR 2024",
    citations: 412,
    score: 8.7,
    grade: "A",
    verdict: "Strong Accept",
    novelty: 88,
    technical: 92,
    clarity: 81,
    impact: 86,
    consensus: "Strong Accept · Accept · Weak Accept · Accept",
    consensusStrength: "strong",
    deep: [
      "§4.4 compute-optimal scaling analysis",
      "§5.2 router stability ablations",
      "Appendix B: token-level depth histograms",
    ],
    skim: [
      "§2 background on conditional computation",
      "§7 broader-impact discussion",
    ],
    reviewers: [
      { handle: "xY3p", rating: 9, label: "Strong Accept", quote: "The compute-optimal scaling analysis in §4.4 is the most rigorous treatment of conditional computation I've seen in two years." },
      { handle: "t4Kw", rating: 8, label: "Accept", quote: "Routing analysis is novel; related-work coverage in §5 is thin. Does not change my recommendation." },
      { handle: "m9aE", rating: 7, label: "Weak Accept", quote: "Solid work. Clarity in §3 could be improved — equations 11–14 are under-explained." },
      { handle: "p2Lq", rating: 8, label: "Accept", quote: "Reproducibility checklist complete; code released and reproduces the headline number." },
    ],
    acceptance: "oral",
    reviewerCount: 4,
  },
  {
    id: "2401.13502",
    title: "Sparse Autoencoders Find Highly Interpretable Features in Language Models",
    authors: "Cunningham, Ewart, Riggs, Huben, Sharkey",
    tldr:
      "Trains overcomplete sparse autoencoders on residual streams of small LMs and shows the recovered features are far more monosemantic than neurons, with reproducible directions across seeds.",
    venue: "ICLR 2024",
    citations: 287,
    score: 8.2,
    grade: "A",
    verdict: "Accept",
    novelty: 79,
    technical: 84,
    clarity: 88,
    impact: 90,
    consensus: "Accept · Accept · Accept",
    consensusStrength: "strong",
    deep: [
      "§3 dictionary-learning objective",
      "§5 monosemanticity evaluation",
      "§6 cross-seed feature stability",
    ],
    skim: [
      "§2 prior work on probing",
      "§7 limitations",
    ],
    reviewers: [
      { handle: "kQ7n", rating: 8, label: "Accept", quote: "Cleanest empirical demonstration to date that overcomplete dictionaries beat neurons on monosemanticity benchmarks." },
      { handle: "rT2c", rating: 8, label: "Accept", quote: "I appreciate the cross-seed reproducibility study — rare and load-bearing for this line of work." },
      { handle: "wH8b", rating: 8, label: "Accept", quote: "Method is simple, presentation is clear. The 'feature splitting' phenomenon deserves more discussion." },
    ],
    acceptance: "poster",
    reviewerCount: 3,
  },
  {
    id: "2403.04132",
    title: "Long-Context Retrieval-Free Reasoning via Compressed Key-Value Caches",
    authors: "Iyer, Bhattacharya, Okafor, Tan, Greenberg",
    tldr:
      "Compresses past KV pairs through a learned low-rank projection so 100k-token reasoning runs in 16k attention; matches retrieval baselines on three long-context benchmarks.",
    venue: "NeurIPS 2024",
    citations: 198,
    score: 7.4,
    grade: "B+",
    verdict: "Accept",
    novelty: 72,
    technical: 81,
    clarity: 70,
    impact: 76,
    consensus: "Accept · Accept · Weak Accept · Weak Accept",
    consensusStrength: "moderate",
    deep: [
      "§3 low-rank projection derivation",
      "§5.1 needle-in-a-haystack results",
      "§5.3 ablation against retrieval baselines",
    ],
    skim: [
      "§2 long-context literature review",
      "§6 deployment considerations",
    ],
    reviewers: [
      { handle: "vN5e", rating: 8, label: "Accept", quote: "The projection is well-motivated and the long-context results are competitive without retrieval — a real contribution." },
      { handle: "sB1f", rating: 7, label: "Weak Accept", quote: "Convincing on synthetic benchmarks; I'd want to see real-world QA before being fully sold." },
      { handle: "eC4r", rating: 8, label: "Accept", quote: "Clean ablations. The compression-quality trade-off curve in §5.3 is the most useful figure." },
      { handle: "dW6t", rating: 7, label: "Weak Accept", quote: "Method is straightforward; novelty is incremental but executed well." },
    ],
    acceptance: "poster",
    reviewerCount: 4,
  },
  {
    id: "2310.06825",
    title: "Mistral 7B",
    authors: "Jiang, Sablayrolles, Mensch, Bamford, Chaplot, et al.",
    tldr:
      "Releases a 7B open-weight model that uses grouped-query attention and sliding-window attention to outperform Llama 2 13B at a fraction of the inference cost.",
    venue: "arXiv 2023",
    citations: 1842,
    score: 7.9,
    grade: "A-",
    verdict: "Accept",
    novelty: 62,
    technical: 84,
    clarity: 90,
    impact: 95,
    consensus: "Accept · Accept · Accept",
    consensusStrength: "strong",
    deep: [
      "§2 architectural choices (GQA + SWA)",
      "§3 evaluation methodology",
      "Appendix A: inference latency benchmarks",
    ],
    skim: [
      "§1 introduction",
      "§4 release-and-licensing discussion",
    ],
    reviewers: [
      { handle: "aB1c", rating: 8, label: "Accept", quote: "Engineering clarity is excellent and the model has had outsized real-world impact." },
      { handle: "mD9k", rating: 8, label: "Accept", quote: "Limited algorithmic novelty but the empirical bar is set responsibly." },
      { handle: "fG2h", rating: 8, label: "Accept", quote: "A well-executed open release. Inference benchmarks are reproducible." },
    ],
    acceptance: "poster",
    reviewerCount: 3,
  },
  {
    id: "2405.14891",
    title: "Verifier-Guided Decoding for Mathematical Reasoning",
    authors: "Sato, Kowalski, Ben-Ari, Onyema",
    tldr:
      "Trains a step-level verifier on reasoning traces and uses it as a beam-search heuristic during decoding; lifts MATH accuracy by 11 points without finetuning the policy.",
    venue: "ICML 2024",
    citations: 87,
    score: 6.8,
    grade: "B",
    verdict: "Weak Accept",
    novelty: 65,
    technical: 74,
    clarity: 67,
    impact: 71,
    consensus: "Weak Accept · Weak Accept · Borderline · Accept",
    consensusStrength: "mixed",
    deep: [
      "§4 verifier training procedure",
      "§5.2 beam-width sensitivity",
    ],
    skim: [
      "§2 related work",
      "§6 cost analysis",
      "Appendix C: failure modes",
    ],
    reviewers: [
      { handle: "qR3w", rating: 7, label: "Weak Accept", quote: "Solid empirical gains on MATH; cost analysis is missing for the verifier itself." },
      { handle: "uE8x", rating: 7, label: "Weak Accept", quote: "Verifier-guided beam search is well-trodden territory but the step-level granularity is a worthwhile twist." },
      { handle: "iA4z", rating: 5, label: "Borderline", quote: "Improvements may not transfer beyond MATH-style problems; the GSM8K results are flat." },
      { handle: "oP5y", rating: 8, label: "Accept", quote: "Clear writing, ablations are honest about where the method struggles." },
    ],
    acceptance: "poster",
    reviewerCount: 4,
  },
  {
    id: "2403.18108",
    title: "Diffusion Policies for Real-Time Robotic Manipulation",
    authors: "Chen, Vargas, O'Sullivan, Pham",
    tldr:
      "Distills denoising policies into a single forward pass via consistency models; achieves real-time control on a 7-DoF arm at 30Hz with comparable success rates.",
    venue: "RSS 2024",
    citations: 134,
    score: 7.1,
    grade: "B+",
    verdict: "Accept",
    novelty: 70,
    technical: 78,
    clarity: 72,
    impact: 74,
    consensus: "Accept · Weak Accept · Accept",
    consensusStrength: "moderate",
    deep: [
      "§3 consistency-model distillation for policies",
      "§5 real-robot results",
    ],
    skim: [
      "§2 diffusion-policy background",
      "§6 simulation appendix",
    ],
    reviewers: [
      { handle: "lJ2k", rating: 8, label: "Accept", quote: "Real-robot 30Hz with comparable success rate is a meaningful systems result." },
      { handle: "nM1v", rating: 6, label: "Weak Accept", quote: "Distillation is well-motivated; novelty is moderate, execution is solid." },
      { handle: "cS7e", rating: 7, label: "Accept", quote: "I would have liked harder manipulation tasks but the closed-loop demos are convincing." },
    ],
    acceptance: "oral",
    reviewerCount: 3,
  },
  {
    id: "2406.02192",
    title: "On the Provable Limits of In-Context Learning Without Pretraining Data Mixing",
    authors: "Goldstein, Marchetti, Adebayo",
    tldr:
      "Constructs a class of tasks for which any transformer trained with disjoint pretraining mixtures provably cannot reach Bayes-optimal in-context performance; aligns with empirical OOD failures.",
    venue: "COLT 2024",
    citations: 41,
    score: 6.2,
    grade: "B",
    verdict: "Borderline",
    novelty: 78,
    technical: 86,
    clarity: 58,
    impact: 60,
    consensus: "Weak Accept · Borderline · Borderline · Accept",
    consensusStrength: "mixed",
    deep: [
      "§3 separation theorem",
      "§4 empirical correspondence",
    ],
    skim: [
      "§5 discussion",
      "Appendix A: full proofs",
    ],
    reviewers: [
      { handle: "yV9o", rating: 7, label: "Weak Accept", quote: "The separation theorem is non-trivial; presentation could be much tighter." },
      { handle: "zU3m", rating: 5, label: "Borderline", quote: "Theory is interesting but the connection to practice is overstated in the abstract." },
      { handle: "hN8d", rating: 5, label: "Borderline", quote: "I struggled with §3 — proof would benefit from a worked example." },
      { handle: "bK4j", rating: 8, label: "Accept", quote: "Best theory paper I've reviewed this cycle on this topic." },
    ],
    acceptance: null,
    reviewerCount: 4,
  },
  {
    id: "2407.10891",
    title: "Symbolic Regression as a Foundation Model Pretraining Task",
    authors: "Hadar, Westbrook, Yamamoto",
    tldr:
      "Argues that pretraining on synthetic symbolic-regression problems yields better mathematical reasoning than code pretraining; results are mixed and replication failed on two of four benchmarks.",
    venue: "TMLR 2024",
    citations: 19,
    score: 4.6,
    grade: "C",
    verdict: "Reject",
    novelty: 60,
    technical: 48,
    clarity: 55,
    impact: 41,
    consensus: "Reject · Borderline · Reject",
    consensusStrength: "moderate",
    deep: ["§4 symbolic curriculum design"],
    skim: [
      "§2 related work",
      "§5 main benchmarks",
      "§6 discussion",
    ],
    reviewers: [
      { handle: "tF6q", rating: 4, label: "Reject", quote: "Replication on the GSM-Hard split shows no improvement — this contradicts the abstract's main claim." },
      { handle: "rZ2s", rating: 5, label: "Borderline", quote: "Interesting framing, weak execution. Needs more careful baselines." },
      { handle: "gW1l", rating: 4, label: "Reject", quote: "I cannot recommend acceptance with the current evidence base." },
    ],
    acceptance: "reject",
    reviewerCount: 3,
  },
];
