"use client";

import { useState } from "react";

export function MethodologyDialog() {
  const [open, setOpen] = useState(false);

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="mt-2 font-sans text-[11px] text-muted underline underline-offset-2 hover:text-ink"
      >
        How is this scored?
      </button>

      {open && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-ink/40 px-4"
          onClick={() => setOpen(false)}
        >
          <div
            className="relative max-h-[90vh] w-full max-w-[560px] overflow-y-auto bg-paper p-8 shadow-xl"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              type="button"
              onClick={() => setOpen(false)}
              className="absolute right-5 top-5 font-sans text-[18px] leading-none text-muted hover:text-ink"
              aria-label="Close"
            >
              ×
            </button>

            <h2 className="text-[22px] font-medium tracking-[-0.01em]">
              Veros Score methodology
            </h2>
            <p className="mt-3 font-sans text-[13px] leading-relaxed text-muted-2">
              The Veros Score is a deterministic 0–10 composite computed
              entirely from peer-reviewer ratings. No black-box ML — the
              formula is open and reproducible.
            </p>

            <h3 className="mt-6 font-sans text-[11px] font-semibold uppercase tracking-[0.14em] text-muted">
              Components
            </h3>
            <dl className="mt-3 space-y-3 font-sans text-[13px]">
              <div>
                <dt className="font-semibold text-ink">
                  Quality (55%){" "}
                  <span className="font-mono font-normal text-muted">
                    weighted_mean(ratings)
                  </span>
                </dt>
                <dd className="text-muted-2">
                  Ratings weighted by reviewer confidence: weight = 0.5 +
                  0.125 × confidence (1–5 scale). A confident reviewer counts
                  more.
                </dd>
              </div>
              <div>
                <dt className="font-semibold text-ink">
                  Consensus (25%){" "}
                  <span className="font-mono font-normal text-muted">
                    clamp(10 − 2σ, 0, 10)
                  </span>
                </dt>
                <dd className="text-muted-2">
                  Lower standard deviation among reviewers → higher consensus
                  component. Split panels are penalised.
                </dd>
              </div>
              <div>
                <dt className="font-semibold text-ink">
                  Acceptance (15%){" "}
                  <span className="font-mono font-normal text-muted">
                    5 + 5 × accepted_flag
                  </span>
                </dt>
                <dd className="text-muted-2">
                  Confirmed acceptance (oral/poster) adds 5 points. Rejection
                  subtracts 5. Unknown venues get the neutral midpoint.
                </dd>
              </div>
              <div>
                <dt className="font-semibold text-ink">
                  Volume bonus (5%){" "}
                  <span className="font-mono font-normal text-muted">
                    min(1, 0.25 × (N − 2))
                  </span>
                </dt>
                <dd className="text-muted-2">
                  Papers with more reviewers carry more evidentiary weight;
                  caps out at N = 6.
                </dd>
              </div>
            </dl>

            <h3 className="mt-6 font-sans text-[11px] font-semibold uppercase tracking-[0.14em] text-muted">
              Grade bands
            </h3>
            <div className="mt-2 grid grid-cols-3 gap-x-4 gap-y-1 font-mono text-[12px]">
              {[
                ["≥ 9.0", "A+"],
                ["≥ 8.3", "A"],
                ["≥ 7.7", "A−"],
                ["≥ 7.0", "B+"],
                ["≥ 6.3", "B"],
                ["≥ 5.7", "B−"],
                ["≥ 5.0", "C+"],
                ["≥ 4.0", "C"],
                ["< 4.0", "D"],
              ].map(([range, grade]) => (
                <div key={grade} className="flex gap-2">
                  <span className="text-muted">{range}</span>
                  <span className="font-semibold text-ink">{grade}</span>
                </div>
              ))}
            </div>

            <p className="mt-6 font-sans text-[12px] text-muted">
              Per-dimension scores (Novelty / Technical / Clarity / Impact) are
              generated by the LLM analysis step and grounded in the actual
              reviewer text — they are not part of the deterministic formula.
            </p>
          </div>
        </div>
      )}
    </>
  );
}
