#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import time
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from sqlalchemy import create_engine, text as sa_text
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.pool import NullPool
from sqlmodel import Session

from app.config import get_settings
from app.db.models import Paper, PaperEdge


@dataclass
class ImportStats:
    papers_inserted: int = 0
    papers_updated: int = 0
    edges_inserted: int = 0
    edges_updated: int = 0


def make_import_engine():
    settings = get_settings()
    return create_engine(
        settings.database_url,
        connect_args={"prepare_threshold": None},
        poolclass=NullPool,
        future=True,
    )


def upsert_papers(db: Session, papers_dict: dict[str, Any], stats: ImportStats) -> None:
    if not papers_dict:
        return

    rows = []
    now = datetime.now(UTC)
    for paper_id, node in papers_dict.items():
        rows.append({
            "id": str(paper_id),
            "title": str(node.get("title") or paper_id),
            "authors": [str(a) for a in node.get("authors", [])],
            "year": node.get("year"),
            "venue": str(node.get("venue")) if node.get("venue") else None,
            "citations": node.get("citation_count"),
            "references_count": node.get("reference_count"),
            "openreview_url": node.get("url"),
            "ingested_at": now,
        })

    # Chunking to avoid massive single transactions
    chunk_size = 1000
    for i in range(0, len(rows), chunk_size):
        chunk = rows[i : i + chunk_size]
        stmt = insert(Paper).values(chunk)
        
        # We only update non-destructive fields to avoid wiping out OpenReview data
        # if there happens to be a collision (unlikely since these use S2 IDs)
        stmt = stmt.on_conflict_do_update(
            index_elements=[Paper.__table__.c.id],
            set_={
                "title": stmt.excluded.title,
                "authors": stmt.excluded.authors,
                "year": stmt.excluded.year,
                "venue": stmt.excluded.venue,
                "citations": stmt.excluded.citations,
                "references_count": stmt.excluded.references_count,
            },
        )
        db.exec(stmt)
        stats.papers_inserted += len(chunk)  # Approximate since it's an upsert


def upsert_edges(db: Session, edges_list: list[dict[str, str]], stats: ImportStats) -> None:
    if not edges_list:
        return

    rows = []
    now = datetime.now(UTC)
    for edge in edges_list:
        rows.append({
            "src_paper_id": str(edge["source"]),
            "dst_paper_id": str(edge["target"]),
            "edge_type": "cites",
            "weight": 1.0,
            "edge_metadata": {},
            "created_at": now,
        })

    chunk_size = 2000
    for i in range(0, len(rows), chunk_size):
        chunk = rows[i : i + chunk_size]
        stmt = insert(PaperEdge).values(chunk)
        stmt = stmt.on_conflict_do_update(
            index_elements=["src_paper_id", "dst_paper_id", "edge_type"],
            set_={
                "weight": stmt.excluded.weight,
            },
        )
        db.exec(stmt)
        stats.edges_inserted += len(chunk)


def import_crawl_json(source: Path) -> ImportStats:
    stats = ImportStats()
    engine = make_import_engine()
    
    print(f"Loading {source} into memory...")
    with source.open("r", encoding="utf-8") as f:
        data = json.load(f)
        
    papers = data.get("papers", {})
    edges = data.get("edges", [])
    
    print(f"Found {len(papers)} papers and {len(edges)} edges to import.")

    with Session(engine) as db:
        # Increase timeout for large bulk inserts
        db.execute(sa_text("SET statement_timeout = 120000"))
        
        print("Upserting papers...")
        start_time = time.monotonic()
        upsert_papers(db, papers, stats)
        db.commit()
        print(f"  Done in {time.monotonic() - start_time:.1f}s")
        
        print("Upserting citation edges...")
        start_time = time.monotonic()
        upsert_edges(db, edges, stats)
        db.commit()
        print(f"  Done in {time.monotonic() - start_time:.1f}s")

    return stats


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import crawled Semantic Scholar citations JSON into the API database."
    )
    parser.add_argument(
        "--source", 
        required=True, 
        help="Path to the JSON file generated by crawl_citations.py."
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    source_path = Path(args.source)
    
    if not source_path.exists():
        print(f"Error: File not found at {source_path}")
        return

    result = import_crawl_json(source_path)

    print("\nImport Complete:")
    print(f"  Papers upserted: {result.papers_inserted:,}")
    print(f"  Edges upserted:  {result.edges_inserted:,}")


if __name__ == "__main__":
    main()
